name: Scan a project with Black Duck
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout the code
      uses: actions/checkout@v2
        
    - name: Run Baseline Black Duck Scan (manual, workflow dispatch)
      if: ${{github.event_name == 'workflow_dispatch'}}
      uses: synopsys-sig-community/blackduck-direct-scan-action@v1
      with:
        bd_url: ${{ secrets.BLACKDUCK_URL }}
        bd_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        bd_trustcert: true
        mode: intelligent
        project: gubraun-insecure-bank
        version: master
      env:
        GITHUB_TOKEN: ${{ github.token }}
          
    - name: Run Black Duck security scan on PR/commit/push
      if: ${{github.event_name != 'workflow_dispatch'}}
      uses: synopsys-sig-community/blackduck-direct-scan-action@v1
      with:
        bd_url: ${{ secrets.BLACKDUCK_URL }}
        bd_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        bd_trustcert: true
        upgrade_major: true
        incremental_results: true
        project: gubraun-insecure-bank
        version: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
